### ISSUE TITLE
[Bug] Cannot query threads by scenario

### ISSUE THREAD

**Issue by Walk4Muscle** [JamborYao/sotool#7]
Server responses 500, e.g. http://10.168.177.44:8008/ThreadsGeneration.svc/GetAllQuestion?fromdate=01/01/2017&todate=02/03/2017&owner=v-guiliu&scenarioId=1&status=All&delivery=3&_=1486089182799

**Comment by JamborYao** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/6415726/22643066/fa0d7ae8-ec97-11e6-83cd-9f76ceb47417.png)
